setwd("/Users/rng/Desktop/cpsc340")
install.packages("rpart")
library(rpart)
data.train <- read.table("2014shortCensusTraining.csv",sep=",",header=T)
summary(data.train)
fit <- rpart(class ~ age, data.train)
print(fit)
fit <- rpart(class ~ age  + education, data.train)
print(fit)